/**
 * Shared, pure helpers every generator uses. Ported from
 * reference/poker-math-trainer.html lines 364-392, with Math.random replaced
 * by an injected Rng so every generator test is deterministic.
 *
 * Poker math itself lives in lib/poker/math.ts — never re-derive it here.
 */
import type { Rng } from "../poker/engine.js";

export const rnd = (n: number, rng: Rng): number => Math.floor(rng() * n);

export const pick = <T>(arr: readonly T[], rng: Rng): T => arr[rnd(arr.length, rng)];

export function shuffled<T>(arr: readonly T[], rng: Rng): T[] {
  const out = arr.slice();
  for (let i = out.length - 1; i > 0; i--) {
    const j = rnd(i + 1, rng);
    [out[i], out[j]] = [out[j], out[i]];
  }
  return out;
}

export const roundTo = (v: number, step: number): number => Math.round(v / step) * step;

/** "a gutshot" / "an open-ended straight draw". */
export const withArticle = (label: string): string =>
  (/^[aeiou]/i.test(label) ? "an " : "a ") + label;

export const money = (v: number): string => "$" + Math.round(v).toLocaleString("en-US");

export const pct = (v: number): string => (v * 100).toFixed(1) + "%";

/** "+$12" / "−$12" — note the true minus sign, U+2212, as the reference uses. */
export const signedMoney = (v: number): string =>
  (v >= 0 ? "+" : "−") + money(Math.abs(v));

/**
 * Dedupe on 2-decimal precision, preserving the first occurrence's value.
 * Note: this hardcodes 2-decimal rounding regardless of minGap, which is correct
 * for current callers (percentages to 1 decimal, whole dollars) but would need
 * to be parameterized if a future caller requires finer precision.
 */
function uniqNums(values: readonly number[]): number[] {
  const seen = new Set<number>();
  const out: number[] = [];
  for (const v of values) {
    const key = Math.round(v * 100) / 100;
    if (!seen.has(key)) {
      seen.add(key);
      out.push(v);
    }
  }
  return out;
}

/**
 * Build exactly `n` distinct numeric choices that always contain `answer`,
 * with no two choices closer than `minGap`. Candidates are tried in random
 * order; if they run out, fillers are generated by scaling the answer.
 */
export function buildOpts(
  answer: number,
  candidates: readonly number[],
  n: number,
  minGap: number,
  rng: Rng
): number[] {
  const gap = minGap || 0.05;
  const out: number[] = [answer];
  const tooClose = (v: number) => out.some((x) => Math.abs(x - v) < gap);

  for (const v of shuffled(uniqNums(candidates), rng)) {
    if (out.length >= n) break;
    if (Number.isFinite(v) && !tooClose(v)) out.push(v);
  }

  // Fillers, when the candidate list was too short or too tightly clustered.
  const base = answer || 10;
  for (let k = 1; out.length < n && k < 60; k++) {
    const v = +(base * (1 + 0.22 * k)).toFixed(1);
    if (Number.isFinite(v) && v !== 0 && !tooClose(v)) out.push(v);
  }
  // Last resort, only reachable for pathological answers: step by minGap.
  for (let k = 1; out.length < n && k < 200; k++) {
    const v = +(answer + gap * k * 1.5).toFixed(2);
    if (Number.isFinite(v) && !tooClose(v)) out.push(v);
  }

  return shuffled(out, rng);
}

/**
 * Integer flavour: exactly `n` distinct integers inside [lo, hi], always
 * containing `answer`. Candidates outside the range are dropped, and padding
 * walks outward from the answer so the range is never violated.
 *
 * @throws {RangeError} if answer is not an integer or outside [lo, hi]
 * @throws {RangeError} if the range [lo, hi] cannot supply n distinct integers
 *   (i.e., if hi - lo + 1 < n)
 */
export function intOptsInRange(
  answer: number,
  candidates: readonly number[],
  n: number,
  lo: number,
  hi: number,
  rng: Rng
): number[] {
  // Validate answer
  if (!Number.isInteger(answer)) {
    throw new RangeError(
      `intOptsInRange: answer must be an integer, got ${answer}`
    );
  }
  if (answer < lo || answer > hi) {
    throw new RangeError(
      `intOptsInRange: answer ${answer} is outside range [${lo}, ${hi}]`
    );
  }

  // Check if range can supply n distinct integers
  const rangeSize = hi - lo + 1;
  if (rangeSize < n) {
    throw new RangeError(
      `intOptsInRange: cannot pick ${n} distinct integers from [${lo}, ${hi}]`
    );
  }

  const valid = (v: number) => Number.isInteger(v) && v >= lo && v <= hi;
  const out: number[] = [answer];
  const push = (v: number) => {
    if (valid(v) && !out.includes(v) && out.length < n) out.push(v);
  };

  for (const v of shuffled(uniqNums(candidates), rng)) push(v);
  // Pad by walking outward from the answer: answer±1, ±2, … staying in range.
  for (let d = 1; out.length < n && d <= hi - lo; d++) {
    push(answer - d);
    push(answer + d);
  }
  return shuffled(out, rng);
}
