-- =====================================================================
-- HCWK Wizard — initial schema
--
-- Ported from StackSchool (FastAPI/SQLAlchemy, 15 tables) with three changes:
--   1. users.id becomes uuid and references auth.users — Supabase Auth owns
--      identity now, so hashed_password / refresh_tokens / password_reset_tokens
--      are gone (Supabase handles all three).
--   2. New social tables: challenges, challenge_hands, challenge_results,
--      activity_events, plus profile fields for public profiles.
--   3. Row Level Security on every user-scoped table.
--
-- Apply with:  supabase db push     (or paste into the SQL editor)
-- =====================================================================

-- ---------------------------------------------------------------------
-- Profiles (replaces StackSchool `users`)
--
-- Supabase convention: never write to auth.users. Mirror it into public.profiles
-- and hang all foreign keys off that.
-- ---------------------------------------------------------------------
create table public.profiles (
  id                uuid primary key references auth.users(id) on delete cascade,
  username          text unique not null,
  display_name      text,
  avatar_url        text,
  bio               text,
  is_public         boolean not null default true,   -- public profile / leaderboard opt-in
  xp                integer not null default 0,
  level             integer not null default 1,
  streak_count      integer not null default 0,
  last_active_date  date,
  created_at        timestamptz not null default now()
);
create index profiles_xp_idx on public.profiles (xp desc);
create index profiles_username_idx on public.profiles (lower(username));

comment on column public.profiles.level is
  'Derived: (xp / 100) + 1. Kept denormalised for cheap leaderboard reads, same as StackSchool.';

-- Auto-create a profile row whenever someone signs up.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, username, display_name)
  values (
    new.id,
    -- collision-safe default; the user can change it later
    coalesce(new.raw_user_meta_data->>'username', split_part(new.email, '@', 1) || '_' || substr(new.id::text, 1, 4)),
    coalesce(new.raw_user_meta_data->>'display_name', split_part(new.email, '@', 1))
  );
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ---------------------------------------------------------------------
-- Content (unchanged shape from StackSchool)
-- ---------------------------------------------------------------------
create table public.modules (
  id           bigint generated by default as identity primary key,
  title        text not null,
  description  text not null default '',
  order_index  integer not null,
  is_active    boolean not null default true,
  created_at   timestamptz not null default now()
);

create type public.lesson_type as enum ('concept', 'quiz', 'drill', 'micro_hand');

-- content_json shape:
-- {
--   "screens": [
--     { "type": "info" | "question" | "drill",
--       "content": "markdown",
--       "choices": [{"id":"a","label":"Fold"}],
--       "correct_choice_id": "b" }
--   ],
--   "skill_tags": ["pot_odds", "position"],
--   "xp_reward": 10
-- }
create table public.lessons (
  id                     bigint generated by default as identity primary key,
  module_id              bigint not null references public.modules(id) on delete cascade,
  lesson_type            public.lesson_type not null,
  title                  text not null,
  order_index            integer not null,
  content_json           jsonb not null,
  estimated_time_seconds integer default 300,
  difficulty             integer default 1,
  version                integer not null default 1,
  is_active              boolean not null default true,
  created_at             timestamptz not null default now()
);
create index lessons_module_idx on public.lessons (module_id, order_index);

create table public.scenarios (
  id            bigint generated by default as identity primary key,
  module_id     bigint not null references public.modules(id) on delete cascade,
  skill_tag     text not null,
  difficulty    integer not null,
  scenario_json jsonb not null,
  version       integer not null default 1,
  is_active     boolean not null default true,
  created_at    timestamptz not null default now()
);
create index scenarios_skill_idx on public.scenarios (skill_tag, difficulty);

-- A deterministic, one-decision poker spot.
-- situation_json: { blinds, effective_stack_bb, hero{seat,position,cards},
--                   villains[], pre_action[], pot_bb, board[] }
-- choices_json:   [{ id, label, action, amount_bb }]
create table public.table_scenarios (
  id                     bigint generated by default as identity primary key,
  module_id              bigint not null references public.modules(id) on delete cascade,
  difficulty             integer not null,
  skill_tag              text not null,
  street                 text not null,
  prompt_title           text not null,
  situation_json         jsonb not null,
  choices_json           jsonb not null,
  correct_choice_id      text not null,
  acceptable_choice_ids  jsonb,
  explanation            text not null,
  rule_of_thumb          text not null,
  is_active              boolean not null default true,
  created_at             timestamptz not null default now()
);
create index table_scenarios_skill_idx on public.table_scenarios (skill_tag, difficulty, street);

-- ---------------------------------------------------------------------
-- Progress
-- ---------------------------------------------------------------------
create table public.attempts (
  id                 bigint generated by default as identity primary key,
  user_id            uuid not null references public.profiles(id) on delete cascade,
  lesson_id          bigint references public.lessons(id) on delete set null,
  scenario_id        bigint references public.scenarios(id) on delete set null,
  table_scenario_id  bigint references public.table_scenarios(id) on delete set null,
  -- NEW: drills generated client-side by lib/poker have no content row to point at
  drill_kind         text,          -- 'outs' | 'pot_odds' | 'preflop' | ...
  drill_payload      jsonb,         -- the generated spot, so results are reproducible
  is_correct         boolean not null,
  selected_choice_id text not null,
  created_at         timestamptz not null default now()
);
create index attempts_user_idx on public.attempts (user_id, created_at desc);

create table public.progress (
  id             bigint generated by default as identity primary key,
  user_id        uuid not null references public.profiles(id) on delete cascade,
  lesson_id      bigint not null references public.lessons(id) on delete cascade,
  status         text not null default 'in_progress',
  completed_at   timestamptz,
  attempts_count integer not null default 0,
  best_score     integer not null default 0,
  unique (user_id, lesson_id)
);

create table public.skill_stats (
  id               bigint generated by default as identity primary key,
  user_id          uuid not null references public.profiles(id) on delete cascade,
  skill_tag        text not null,
  total_attempts   integer not null default 0,
  correct_attempts integer not null default 0,
  unique (user_id, skill_tag)
);

create table public.user_daily_activity (
  id                  bigint generated by default as identity primary key,
  user_id             uuid not null references public.profiles(id) on delete cascade,
  date                date not null,
  xp_earned           integer not null default 0,
  lessons_completed   integer not null default 0,
  scenarios_completed integer not null default 0,
  created_at          timestamptz not null default now(),
  unique (user_id, date)
);
create index user_daily_activity_idx on public.user_daily_activity (user_id, date desc);

-- ---------------------------------------------------------------------
-- Daily content
-- ---------------------------------------------------------------------
create table public.daily_content (
  id           bigint generated by default as identity primary key,
  date         date not null unique,
  content_type text not null,
  lesson_id    bigint references public.lessons(id) on delete set null,
  scenario_id  bigint references public.scenarios(id) on delete set null,
  created_at   timestamptz not null default now()
);

create table public.user_daily_completions (
  id           bigint generated by default as identity primary key,
  user_id      uuid not null references public.profiles(id) on delete cascade,
  date         date not null,
  content_type text not null,
  content_id   bigint not null,
  xp_awarded   integer not null default 0,
  created_at   timestamptz not null default now(),
  unique (user_id, date)
);

-- ---------------------------------------------------------------------
-- Friends
-- ---------------------------------------------------------------------
create table public.friend_requests (
  id           bigint generated by default as identity primary key,
  from_user_id uuid not null references public.profiles(id) on delete cascade,
  to_user_id   uuid not null references public.profiles(id) on delete cascade,
  status       text not null default 'pending',   -- pending | accepted | declined
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  unique (from_user_id, to_user_id),
  check (from_user_id <> to_user_id)
);
create index friend_requests_to_idx on public.friend_requests (to_user_id, status);

-- Stored bidirectionally (two rows per friendship), matching StackSchool.
create table public.friends (
  id             bigint generated by default as identity primary key,
  user_id        uuid not null references public.profiles(id) on delete cascade,
  friend_user_id uuid not null references public.profiles(id) on delete cascade,
  created_at     timestamptz not null default now(),
  unique (user_id, friend_user_id),
  check (user_id <> friend_user_id)
);

-- ---------------------------------------------------------------------
-- NEW: head-to-head challenges
--
-- A challenge is a fixed set of hands both players answer, so scores are
-- comparable. Hands are frozen at creation time into challenge_hands.
-- ---------------------------------------------------------------------
create table public.challenges (
  id            uuid primary key default gen_random_uuid(),
  creator_id    uuid not null references public.profiles(id) on delete cascade,
  opponent_id   uuid references public.profiles(id) on delete cascade,  -- null = open challenge
  drill_kind    text not null,             -- which drill this tests
  hand_count    integer not null default 10,
  status        text not null default 'pending',  -- pending | active | complete | expired
  expires_at    timestamptz not null default (now() + interval '7 days'),
  created_at    timestamptz not null default now()
);
create index challenges_opponent_idx on public.challenges (opponent_id, status);
create index challenges_creator_idx on public.challenges (creator_id, status);

create table public.challenge_hands (
  id           bigint generated by default as identity primary key,
  challenge_id uuid not null references public.challenges(id) on delete cascade,
  order_index  integer not null,
  payload      jsonb not null,   -- the frozen generated spot
  answer       jsonb not null,   -- correct answer + explanation data
  unique (challenge_id, order_index)
);

create table public.challenge_results (
  id             bigint generated by default as identity primary key,
  challenge_id   uuid not null references public.challenges(id) on delete cascade,
  user_id        uuid not null references public.profiles(id) on delete cascade,
  correct_count  integer not null default 0,
  total_count    integer not null default 0,
  elapsed_ms     integer,
  answers        jsonb,
  completed_at   timestamptz not null default now(),
  unique (challenge_id, user_id)
);

-- ---------------------------------------------------------------------
-- NEW: activity feed
--
-- Append-only events. Fan-out happens at read time by joining friends —
-- simpler and perfectly fast at friend-graph scale.
-- ---------------------------------------------------------------------
create table public.activity_events (
  id         bigint generated by default as identity primary key,
  user_id    uuid not null references public.profiles(id) on delete cascade,
  kind       text not null,   -- lesson_complete | streak_milestone | level_up | challenge_win | ...
  payload    jsonb not null default '{}',
  created_at timestamptz not null default now()
);
create index activity_events_user_time_idx on public.activity_events (user_id, created_at desc);
create index activity_events_time_idx on public.activity_events (created_at desc);

-- ---------------------------------------------------------------------
-- Helper: is the current user friends with X?
-- ---------------------------------------------------------------------
create or replace function public.is_friend(target uuid)
returns boolean
language sql stable security definer set search_path = public
as $$
  select exists (
    select 1 from public.friends
    where user_id = auth.uid() and friend_user_id = target
  );
$$;

-- ---------------------------------------------------------------------
-- Row Level Security
--
-- Content tables are world-readable to signed-in users and writable only by
-- the service role (seeding/admin). Everything user-scoped is owner-only,
-- with friend visibility where the product needs it.
-- ---------------------------------------------------------------------
alter table public.profiles              enable row level security;
alter table public.modules               enable row level security;
alter table public.lessons               enable row level security;
alter table public.scenarios             enable row level security;
alter table public.table_scenarios       enable row level security;
alter table public.attempts              enable row level security;
alter table public.progress              enable row level security;
alter table public.skill_stats           enable row level security;
alter table public.user_daily_activity   enable row level security;
alter table public.daily_content         enable row level security;
alter table public.user_daily_completions enable row level security;
alter table public.friend_requests       enable row level security;
alter table public.friends               enable row level security;
alter table public.challenges            enable row level security;
alter table public.challenge_hands       enable row level security;
alter table public.challenge_results     enable row level security;
alter table public.activity_events        enable row level security;

-- Content: readable by any authenticated user.
create policy "content readable" on public.modules         for select to authenticated using (true);
create policy "content readable" on public.lessons         for select to authenticated using (true);
create policy "content readable" on public.scenarios       for select to authenticated using (true);
create policy "content readable" on public.table_scenarios for select to authenticated using (true);
create policy "content readable" on public.daily_content   for select to authenticated using (true);

-- Profiles: you can always see your own; others only if public or a friend.
create policy "read own profile"    on public.profiles for select to authenticated
  using (id = auth.uid() or is_public or public.is_friend(id));
create policy "update own profile"  on public.profiles for update to authenticated
  using (id = auth.uid()) with check (id = auth.uid());

-- Owner-only tables.
create policy "own attempts"    on public.attempts    for all to authenticated
  using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "own progress"    on public.progress    for all to authenticated
  using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "own daily"       on public.user_daily_completions for all to authenticated
  using (user_id = auth.uid()) with check (user_id = auth.uid());

-- Stats and activity: yours, plus friends' (needed for the feed and leaderboards).
create policy "own or friend skill stats" on public.skill_stats for select to authenticated
  using (user_id = auth.uid() or public.is_friend(user_id));
create policy "write own skill stats" on public.skill_stats for all to authenticated
  using (user_id = auth.uid()) with check (user_id = auth.uid());

create policy "own or friend activity" on public.user_daily_activity for select to authenticated
  using (user_id = auth.uid() or public.is_friend(user_id));
create policy "write own activity" on public.user_daily_activity for all to authenticated
  using (user_id = auth.uid()) with check (user_id = auth.uid());

create policy "feed visible" on public.activity_events for select to authenticated
  using (user_id = auth.uid() or public.is_friend(user_id));
create policy "write own events" on public.activity_events for insert to authenticated
  with check (user_id = auth.uid());

-- Friends: see requests addressed to or from you.
create policy "see own requests" on public.friend_requests for select to authenticated
  using (from_user_id = auth.uid() or to_user_id = auth.uid());
create policy "send requests" on public.friend_requests for insert to authenticated
  with check (from_user_id = auth.uid());
create policy "respond to requests" on public.friend_requests for update to authenticated
  using (to_user_id = auth.uid());

create policy "see own friends" on public.friends for select to authenticated
  using (user_id = auth.uid() or friend_user_id = auth.uid());

-- Challenges: visible to both participants.
create policy "see own challenges" on public.challenges for select to authenticated
  using (creator_id = auth.uid() or opponent_id = auth.uid() or opponent_id is null);
create policy "create challenges" on public.challenges for insert to authenticated
  with check (creator_id = auth.uid());

-- Challenge hands are only readable by participants.
create policy "see challenge hands" on public.challenge_hands for select to authenticated
  using (exists (
    select 1 from public.challenges c
    where c.id = challenge_id and (c.creator_id = auth.uid() or c.opponent_id = auth.uid())
  ));

create policy "see challenge results" on public.challenge_results for select to authenticated
  using (exists (
    select 1 from public.challenges c
    where c.id = challenge_id and (c.creator_id = auth.uid() or c.opponent_id = auth.uid())
  ));
create policy "write own results" on public.challenge_results for insert to authenticated
  with check (user_id = auth.uid());

-- ---------------------------------------------------------------------
-- Leaderboard view — respects is_public, safe to select from the client.
-- ---------------------------------------------------------------------
create view public.leaderboard
with (security_invoker = true)
as
  select id, username, display_name, avatar_url, xp, level, streak_count
  from public.profiles
  where is_public
  order by xp desc;
