-- M8.5B: new-user placement assessment.
--
-- A new account started at level 1 with no history, so the deterministic
-- recommender had nothing to work from and served the first lesson of the
-- first module to everyone — a player who already knows pot odds cold was
-- taught what a pot is. A short assessment, drawn from the same tested
-- generators as the drills, places them instead.
--
-- Placement is NOT practice. It writes nothing to `attempts`, awards no XP,
-- touches no streak and never lands in `skill_stats`, so it cannot inflate any
-- aggregate. These tables are its own record.

create table public.placement_assessments (
  id                 bigint generated by default as identity primary key,
  user_id            uuid not null references public.profiles(id) on delete cascade,
  -- Both versions are stored, not derived. A later re-placement has to be
  -- comparable with this one, and a changed generator must never silently
  -- reinterpret an old score: if either version differs, the scores are from a
  -- different instrument and analytics has to say so rather than average them.
  assessment_version integer not null,
  generator_version  integer not null,
  -- Every question is regenerated from (assessment_version, seed), so a
  -- reported bad placement question can be reproduced exactly.
  seed               bigint  not null,
  status             text    not null default 'in_progress'
                       check (status in ('in_progress', 'completed', 'skipped')),
  question_count     integer not null check (question_count > 0),
  -- Per-skill-tag placement scores, derived server-side from the responses
  -- below when the assessment completes. Empty until then.
  scores             jsonb   not null default '{}'::jsonb,
  -- Per-drill-kind starting difficulty the result implies.
  levels             jsonb   not null default '{}'::jsonb,
  -- 0-based index into the active module list — where the path should start.
  entry_module_index integer,
  started_at         timestamptz not null default now(),
  completed_at       timestamptz
);

-- One row per user is the common case, but a retake adds another, so the
-- lookup is "the newest row for this user".
create index placement_assessments_user_idx
  on public.placement_assessments (user_id, started_at desc, id desc);

create table public.placement_responses (
  id             bigint generated by default as identity primary key,
  assessment_id  bigint  not null references public.placement_assessments(id)
                   on delete cascade,
  question_index integer not null check (question_index >= 0),
  -- drill_kind and skill_tag are written from the SERVER's copy of the
  -- blueprint at this index, never from the request body: the client picks
  -- neither which question it was asked nor what skill it measures.
  drill_kind     text    not null,
  skill_tag      text    not null,
  response_type  text    not null check (response_type in ('answer', 'unsure')),
  is_correct     boolean not null,
  answer         text    not null,
  created_at     timestamptz not null default now(),
  -- Idempotency: a retried submit for the same question updates in place
  -- rather than double-counting the tag.
  unique (assessment_id, question_index)
);

alter table public.placement_assessments enable row level security;
alter table public.placement_responses   enable row level security;

create policy "own placement assessments" on public.placement_assessments
  for all to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

-- Responses are owner-scoped through their parent. The subquery is the only
-- link between a response and a user, so it must appear in both USING (reads,
-- updates, deletes) and WITH CHECK (inserts and the post-image of updates) —
-- a policy with only USING would let anyone insert a response against someone
-- else's assessment.
create policy "own placement responses" on public.placement_responses
  for all to authenticated
  using (
    exists (
      select 1 from public.placement_assessments a
      where a.id = placement_responses.assessment_id and a.user_id = auth.uid()
    )
  )
  with check (
    exists (
      select 1 from public.placement_assessments a
      where a.id = placement_responses.assessment_id and a.user_id = auth.uid()
    )
  );

-- Lessons the assessment showed the player already knows. A distinct status,
-- not 'completed': they did not take the lesson, and conflating the two would
-- make the completion meter claim work that never happened. The learning path
-- treats it as satisfied when choosing the next lesson.
comment on column public.progress.status is
  'in_progress | completed | placed_out. placed_out means the M8.5B placement assessment satisfied this lesson without the player taking it.';
